---
# This Playbook configure firewall 'ferm'
- name: Install Ferm
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: ferm
    state: present

- name: Ferm | Display rules var
  debug: var="{{ferm_rules}}"

- name: Ferm | Make sure the directory for firewall rules exist
  file: path=/etc/ferm state=directory owner=root group=root

- name: Ferm | Create config directory
  file: path=/etc/ferm/ferm.d state=directory owner=root group=root

- name: Ferm | Include ferm.d directory
  lineinfile: dest=/etc/ferm/ferm.conf line="@include 'ferm/ferm.d/';" backup=yes insertbefore=BOF create=yes
  when: ansible_os_family == "Debian"

- name: Ferm | Include ferm.d directory
  lineinfile: dest=/etc/ferm.conf line="@include 'ferm.d/';" backup=yes insertbefore=BOF create=yes
  when: ansible_os_family == "RedHat"

- name: Ferm | Create the ferm conf files
  template: src=ferm.conf.j2 dest=/etc/ferm/ferm.d/{{item.key}}.conf mode=0655 owner=root group=root backup=yes
  with_dict: ferm_rules
  notify:
    - reload ferm


- meta: flush_handlers

- name: reload ferm
  service: name=ferm state=restarted
  changed_when: False
